### ISSUE TITLE
Suggestion: making Social Media friendly URLs

### ISSUE THREAD

**Issue by msurguy** [anvaka/query-state#4]
In order to share the URLs generated by this query state library on social media (twitter and facebook), the URLs have to be encoded a bit differently. 

I propose implementing a new method that will return social media friendly encoded URL

**Comment by msurguy** [comment]
As an example, I have to do the following to get Twitter friendly URLs:
```
const sharingURL = (encodeURIComponent(projectURL + queryPrefix) + query.stringify(qs.get())).split('%20').join('').split('=').join('%3D').split('&').join('%26')
```

**Comment by msurguy** [comment]
@anvaka nevermind! I was able to figure it out without too much hassle. Looks like the following way is working: 
```js
const queryPrefix = appendQuery ? '#?' : ''
const encodedURL = query.stringify(qs.get())
this.sharingURL = encodeURIComponent(projectURL + queryPrefix + encodedURL)
```

**Comment by anvaka** [comment]
You can also use like `userSearch` parameter:

``` js
var qs = queryState({
  answer: 42
}, {
  useSearch: true
});
```

See more details here https://github.com/anvaka/query-state#search-instead-of-hash
